title: The Manuscript
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
base_font: nunito-sans
palette: blue
header:
  logo_img: images/logo-the-manuscript-horizontal.png
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Episodes
      url: /index#episodes
      style: link
    - label: Subscribe
      url: /subscribe
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/logo-the-manuscript.png
      image_url: /
      image_alt: Footer logo
      content: Writing & Tech
    - type: footer_nav
      title: Talk to us
      nav_links:
        # - label: About Us
        #   url: /about
        #   style: link
        # - label: Blog
        #   url: /blog
        #   style: link
        - label: Subscribe
          url: /subscribe
          style: link
        - label: Contact
          url: mailto:themanuscriptpodcast@gmail.com
          style: link
    - type: footer_nav
      title: Follow us
      nav_links:
        - label: Twitter
          url: 'https://twitter.com/TheManu_script_'
          style: link
          has_icon: true
          icon: twitter
          icon_position: left
        # - label: LinkedIn
        #   url: 'https://www.linkedin.com/'
        #   style: link
        #   has_icon: true
        #   icon: linkedin
        #   icon_position: left
        # - label: GitHub
        #   url: 'https://github.com/'
        #   style: link
        #   has_icon: true
        #   icon: github
        #   icon_position: left
    - type: footer_form
      title: Subscribe
      content: Stay up to date with what we're doing.
      form_id: contactForm
      hide_labels: true
      form_fields:
        - input_type: email
          name: email
          label: Email
          default_value: Email address
          is_required: true
      submit_label: Subscribe
  has_nav: false
  nav_links:
    - label: Terms of Service
      url: /terms-of-service
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  content: >-
    &copy; The Manuscript. All rights reserved.
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https:themanuscript.co'
